# Redirect non-www to www
[[redirects]]
  from = "https://medsexpresspharmacy.com/*"
  to = "https://www.medsexpresspharmacy.com/:splat"
  status = 301
  force = true

# Redirect netlify.app to www
[[redirects]]
  from = "https://medsexpresspharmacy.netlify.app/*"
  to = "https://www.medsexpresspharmacy.com/:splat"
  status = 301
  force = true

# Custom 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404